# Generated by Django 5.2.1 on 2025-05-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
